# **線形代数**

In [4]:
import numpy as np
from scipy import linalg

In [6]:
a = np.array([[3, 1, 1], [1, 2, 1], [0, -1, 1]])
b = np.array([1, 2, 3])
np.linalg.inv(a) # 逆行列

array([[ 0.42857143, -0.28571429, -0.14285714],
       [-0.14285714,  0.42857143, -0.28571429],
       [-0.14285714,  0.42857143,  0.71428571]])

In [7]:
np.linalg.solve(a, b)

array([-0.57142857, -0.14285714,  2.85714286])

LU分解

$$
\begin{align}
A = PLU
\end{align}
$$

ときたい方程式は ${\bf Ax}={\bf b}$ なので、

$$
\begin{align}
{\bf Pz} &= {\bf b} \\
{\bf Ly} &= {\bf z} \\
{\bf Ux} &= {\bf y}
\end{align}
$$

LU分解により連立方程式を解く方法

In [8]:
a = np.array([[3, 1, 1], [1, 2, 1], [0, -1, 1]])
b = np.array([1, 2, 3])

lu, p = linalg.lu_factor(a)
linalg.lu_solve((lu, p), b)

array([-0.57142857, -0.14285714,  2.85714286])