## 乱数

`rand`: 区間 $[0, 1)$ での一様乱数  
`randint`: 与えられた範囲で整数値の乱数を返す。

In [1]:
import numpy as np

In [6]:
np.random.rand()

0.8948283941208127

In [7]:
np.random.rand()

0.1329305836932465

In [8]:
np.random.rand(3, 2)

array([[0.13182595, 0.48769159],
       [0.80498031, 0.00785802],
       [0.79741254, 0.70559846]])

In [9]:
np.random.rand(5)

array([0.09157373, 0.73322179, 0.35171094, 0.14972513, 0.32818324])

In [15]:
np.random.randint(4)

1

In [13]:
np.random.randint(10, 20)

10

In [16]:
np.random.randint(5, size=(3, 3))

array([[4, 1, 1],
       [4, 4, 4],
       [4, 3, 4]])

In [17]:
def throw_dice(n):
    return np.random.randint(1, 7, size=7).sum()

In [20]:
print(throw_dice(10))
print(throw_dice(10))
print(throw_dice(10))

23
24
16


乱数列を選択するのが乱数のたね(シード)と呼ばれるもの。乱数の種は整数値。同じ種で初期化すれば同じ欄数列が得られるということが保証されている。

In [22]:
np.random.seed(10)
np.random.rand(5)

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [23]:
np.random.seed(10)
np.random.rand(5) # 同じ乱数列を選択しているので、上と同じ数になる。

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701])

In [24]:
np.random.seed(100)
np.random.rand(5) # シードを変更

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [26]:
np.random.seed(100)
np.random.rand(5) # シードを変更。上記と同じ結果になっている。

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [27]:
def throw_dice(n, random_seed=10):
    np.random.seed(random_seed)
    return np.random.randint(1, 7, size=n).sum()

In [29]:
print(throw_dice(10))
print(throw_dice(10))
print(throw_dice(100))
print(throw_dice(100))

34
34
328
328


In [54]:
class Dice(object):
    
    def __init__(self, random_seed=None):
        self.random_state_ = np.random.RandomState(random_seed)
        self.__sum = 0
        
    def throw(self):
        self.__sum += self.random_state_.randint(1, 7)
        
    @property
    def sum(self):
        return self.__sum

In [55]:
d1 = Dice(123)
d2 = Dice(123)

In [56]:
for _ in range(10):
    d1.throw()
    d2.throw()

In [57]:
print(d1.sum)
print(d2.sum)

34
34
